version: '3.8'

networks:
  agent_network:
    driver: bridge

services:
  elegantrl:
    build: 
      context: ./agents/elegantrl
    networks:
      - agent_network
    volumes:
      - ./shared:/app/shared

  rllib:
    build:
      context: ./agents/rllib
    networks:
      - agent_network
    volumes:
      - ./shared:/app/shared

  stablebaselines3:
    build:
      context: ./agents/stablebaselines3
    networks:
      - agent_network
    volumes:
      - ./shared:/app/shared

  portfolio_optimization:
    build:
      context: ./agents/portfolio_optimization
    networks:
      - agent_network
    volumes:
      - ./shared:/app/shared

  deephedging:
    build:
      context: ./agents/deephedging
    networks:
      - agent_network
    volumes:
      - ./shared:/app/shared

  crewai:
    build:
      context: ./agents/crewai
    networks:
      - agent_network
    volumes:
      - ./shared:/app/shared
